arb-dir: lib/l10n
template-arb-file: app_en.arb
output-dir: lib/l10n/gen
output-localization-file: app_localizations.dart
nullable-getter: false
untranslated-messages-file: lib/l10n/_untranslated.json
